# docker-compose.yml
version: '3.9'

services:
  legal-ml-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: legal-ml-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - vectordb_data:/app/src/vectordb
    restart: always

volumes:
  vectordb_data:
